name: "Update"
on:
  push:
    branches:
      - main
    paths:
      - "*"
      - "!README.md"
jobs:
  brew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            Updated jobs from Greenhouse
            skip-checks: true
        run: |
          # Hard-code user config
          git config user.email "luke@thisis.la"
          git config user.name "Luke Watts"
          git config --get-regexp "user\.(name|email)"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Only commit and push if we have changes
          git commit --allow-empty -m "feat: hourly update"; git push origin main