name: "Update and Release"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  brew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Commit
        run: |
          # Hard-code user config
          git config user.email "luke@thisis.la"
          git config user.name "Luke Watts"
          git config --get-regexp "user\.(name|email)"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Checkout the branch so we can push back to it
          git checkout main
          git commit --allow-empty -m "feat: Hourly update $(date)"; git push origin main
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
